/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.netbeans.vns.javafx.form.edit;

import java.io.File;
import javax.swing.SwingUtilities;
import org.vns.javafx.dock.DockBorderPane;
import org.vns.javafx.dock.DockNode;

import javafx.application.Application;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.paint.Color;
import org.openide.filesystems.FileObject;
import org.openide.filesystems.FileUtil;
import org.vns.javafx.dock.api.DockRegistry;
import org.vns.javafx.dock.api.Dockable;

/**
 *
 * @author Valery
 */
public class JFXPalettePanel extends JFXPanel {

    private DockNode formNode;
    private DockBorderPane mainBorderPane;
    //private StackPane mainBorderPane;

    public JFXPalettePanel() {
        initComponents();
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                initGUI();
            }
        });
    }

    @Override
    public String getName() {
        return "FxFormVisualElement";
    }

    private void initGUI() {

        Platform.setImplicitExit(false);

        Platform.runLater(new Runnable() {
            @Override
            public void run() {
                Util.out("JFXPalettePanel Platform.runLater");
                initFX();
                Application.setUserAgentStylesheet(Application.STYLESHEET_MODENA);
                Dockable.initDefaultStylesheet(null);

            }
        });
    }

    Scene scene = null;

    private void initFX() {
        // This method is invoked on the JavaFX thread
        Util.out(" --- initFX");
        scene = createScene();
        setScene(scene);
        //DockRegistry.register(scene.getWindow());
    }

    private Scene createScene() {
        Util.out(" --- PALETE createScene");
        mainBorderPane = new DockBorderPane();
        //mainBorderPane = new StackPane();
        scene = new Scene(mainBorderPane, Color.YELLOW);

        formNode = new DockNode("PALETTE Edit DockNode");
        formNode.setStyle("-fx-background-color: green;");

        DockNode sceneGraph = new DockNode("PALETTE Node hierarchy");
        Button sgBtn1 = new Button("PALETTE Scene Graph Btn");
        DockRegistry.makeDockable(sgBtn1);
        formNode.getProperties().put("PALETTE fxdocking:dockable:scene", scene);
        formNode.setContent(sgBtn1);
        mainBorderPane.setCenter(formNode);
        sgBtn1.setOnAction(a -> {
            Util.out(" **** PALETE ButtonPressed window=" + sgBtn1.getScene().getWindow());
            File f = new File("D:\\JavaFX-Tests\\JavaApplication5\\src\\javaapplication5\\Sanple01_design.java");
            FileObject dfo = FileUtil.toFileObject(f);    
            FxFormRefactoring.rename(dfo, "button1", "myButton");

        });
        return (scene);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    }// </editor-fold>                        

}
